/**
 * Commune Schema Definition for Firebase Firestore
 * 
 * Đây là file định nghĩa schema cho Commune trong Firebase.
 * Firebase Firestore không có schema validation tự động như MongoDB,
 * nên file này dùng để:
 * 1. Tham khảo cấu trúc dữ liệu
 * 2. Validation trong code
 * 3. Documentation
 */

const COMMUNE_SCHEMA = {
    // Required fields
    ma_xa: {
        type: "string",
        required: true,
        description: "Mã xã/phường/thị trấn"
    },
    ten_xa: {
        type: "string",
        required: true,
        description: "Tên xã/phường/thị trấn"
    },
    name: {
        type: "string",
        required: true,
        description: "Tên tiếng Anh hoặc tên khác"
    },
    loai: {
        type: "string",
        required: true,
        description: "Loại đơn vị (Xã, Phường, Thị trấn)"
    },
    cap: {
        type: "number",
        required: true,
        description: "Cấp hành chính"
    },
    ma_tinh: {
        type: "string",
        required: true,
        description: "Mã tỉnh/thành phố"
    },
    ten_tinh: {
        type: "string",
        required: true,
        description: "Tên tỉnh/thành phố"
    },
    
    // Optional fields
    dan_so: {
        type: "number",
        required: false,
        nullable: true,
        description: "Dân số"
    },
    dtich_km2: {
        type: "number",
        required: false,
        nullable: true,
        description: "Diện tích (km²)"
    },
    matdo_km2: {
        type: "number",
        required: false,
        nullable: true,
        description: "Mật độ dân số (người/km²)"
    },
    address: {
        type: "string",
        required: false,
        nullable: true,
        description: "Địa chỉ"
    },
    tru_so: {
        type: "string",
        required: false,
        nullable: true,
        description: "Trụ sở"
    },
    sap_nhap: {
        type: "string",
        required: false,
        nullable: true,
        description: "Tình trạng sáp nhập"
    },
    
    // Auto-generated fields (Firebase timestamps)
    createdAt: {
        type: "timestamp",
        required: false,
        autoGenerated: true,
        description: "Thời gian tạo (tự động)"
    },
    updatedAt: {
        type: "timestamp",
        required: false,
        autoGenerated: true,
        description: "Thời gian cập nhật (tự động)"
    }
};

/**
 * Helper function để parse number
 */
const parseNumber = (value) => {
    if (value === null || value === undefined || value === "") {
        return null;
    }
    const num = Number(value);
    return Number.isFinite(num) ? num : null;
};

/**
 * Validation function cho commune data
 */
const validateCommune = (data, isUpdate = false) => {
    const errors = [];

    // Required fields khi tạo mới
    if (!isUpdate) {
        if (!data.ma_xa || typeof data.ma_xa !== "string" || data.ma_xa.trim() === "") {
            errors.push("ma_xa is required and must be a non-empty string");
        }
        if (!data.ten_xa || typeof data.ten_xa !== "string" || data.ten_xa.trim() === "") {
            errors.push("ten_xa is required and must be a non-empty string");
        }
        if (!data.name || typeof data.name !== "string" || data.name.trim() === "") {
            errors.push("name is required and must be a non-empty string");
        }
        if (!data.loai || typeof data.loai !== "string" || data.loai.trim() === "") {
            errors.push("loai is required and must be a non-empty string");
        }
        if (data.cap === undefined || data.cap === null) {
            errors.push("cap is required and must be a number");
        } else {
            const capNum = parseNumber(data.cap);
            if (capNum === null) {
                errors.push("cap must be a valid number");
            }
        }
        if (!data.ma_tinh || typeof data.ma_tinh !== "string" || data.ma_tinh.trim() === "") {
            errors.push("ma_tinh is required and must be a non-empty string");
        }
        if (!data.ten_tinh || typeof data.ten_tinh !== "string" || data.ten_tinh.trim() === "") {
            errors.push("ten_tinh is required and must be a non-empty string");
        }
    }

    // Optional fields validation
    if (data.ma_xa !== undefined) {
        if (typeof data.ma_xa !== "string" || data.ma_xa.trim() === "") {
            errors.push("ma_xa must be a non-empty string");
        }
    }

    if (data.ten_xa !== undefined) {
        if (typeof data.ten_xa !== "string" || data.ten_xa.trim() === "") {
            errors.push("ten_xa must be a non-empty string");
        }
    }

    if (data.name !== undefined) {
        if (typeof data.name !== "string" || data.name.trim() === "") {
            errors.push("name must be a non-empty string");
        }
    }

    if (data.loai !== undefined) {
        if (typeof data.loai !== "string" || data.loai.trim() === "") {
            errors.push("loai must be a non-empty string");
        }
    }

    if (data.cap !== undefined && data.cap !== null) {
        const capNum = parseNumber(data.cap);
        if (capNum === null) {
            errors.push("cap must be a valid number");
        }
    }

    if (data.ma_tinh !== undefined) {
        if (typeof data.ma_tinh !== "string" || data.ma_tinh.trim() === "") {
            errors.push("ma_tinh must be a non-empty string");
        }
    }

    if (data.ten_tinh !== undefined) {
        if (typeof data.ten_tinh !== "string" || data.ten_tinh.trim() === "") {
            errors.push("ten_tinh must be a non-empty string");
        }
    }

    // Validate number fields
    const numberFields = ["dan_so", "dtich_km2", "matdo_km2"];
    for (const field of numberFields) {
        if (data[field] !== undefined && data[field] !== null) {
            const num = parseNumber(data[field]);
            if (num === null) {
                errors.push(`${field} must be a valid number or null`);
            }
        }
    }

    // Validate string fields (optional)
    const stringFields = ["address", "tru_so", "sap_nhap"];
    for (const field of stringFields) {
        if (data[field] !== undefined && data[field] !== null) {
            if (typeof data[field] !== "string") {
                errors.push(`${field} must be a string or null`);
            }
        }
    }

    return {
        isValid: errors.length === 0,
        errors
    };
};

/**
 * Sanitize commune data - loại bỏ các field không hợp lệ và parse numbers
 */
const sanitizeCommuneData = (data) => {
    const allowedFields = [
        "ma_xa",
        "ten_xa",
        "name",
        "loai",
        "cap",
        "ma_tinh",
        "ten_tinh",
        "dan_so",
        "dtich_km2",
        "matdo_km2",
        "address",
        "tru_so",
        "sap_nhap"
    ];

    const sanitized = {};
    for (const field of allowedFields) {
        if (data[field] !== undefined) {
            // Parse number fields
            if (["cap", "dan_so", "dtich_km2", "matdo_km2"].includes(field)) {
                sanitized[field] = parseNumber(data[field]);
            } else {
                sanitized[field] = data[field];
            }
        }
    }

    return sanitized;
};

/**
 * Get default commune data
 */
const getDefaultCommuneData = () => {
    return {
        dan_so: null,
        dtich_km2: null,
        matdo_km2: null,
        address: null,
        tru_so: null,
        sap_nhap: null
    };
};

module.exports = {
    COMMUNE_SCHEMA,
    validateCommune,
    sanitizeCommuneData,
    getDefaultCommuneData,
    parseNumber
};

