/**
 * Contact Schema Definition for Firebase Firestore
 * 
 * Đây là file định nghĩa schema cho Contact trong Firebase.
 * Firebase Firestore không có schema validation tự động như MongoDB,
 * nên file này dùng để:
 * 1. Tham khảo cấu trúc dữ liệu
 * 2. Validation trong code
 * 3. Documentation
 */

const CONTACT_SCHEMA = {
    // Required fields
    ma_xa: {
        type: "string",
        required: true,
        description: "Mã xã/phường/thị trấn"
    },
    ten_xa: {
        type: "string",
        required: true,
        description: "Tên xã/phường/thị trấn"
    },
    chief: {
        type: "string",
        required: true,
        description: "Tên người đứng đầu"
    },
    cap: {
        type: "number",
        required: true,
        description: "Cấp hành chính"
    },
    
    // Optional fields
    mobile: {
        type: "string",
        required: false,
        nullable: true,
        description: "Số điện thoại (có thể null)"
    },
    
    // Auto-generated fields (Firebase timestamps)
    createdAt: {
        type: "timestamp",
        required: false,
        autoGenerated: true,
        description: "Thời gian tạo (tự động)"
    },
    updatedAt: {
        type: "timestamp",
        required: false,
        autoGenerated: true,
        description: "Thời gian cập nhật (tự động)"
    }
};

/**
 * Validation function cho contact data
 */
const validateContact = (data, isUpdate = false) => {
    const errors = [];

    // Required fields khi tạo mới
    if (!isUpdate) {
        if (!data.ma_xa || typeof data.ma_xa !== "string" || data.ma_xa.trim() === "") {
            errors.push("ma_xa is required and must be a non-empty string");
        }
        if (!data.ten_xa || typeof data.ten_xa !== "string" || data.ten_xa.trim() === "") {
            errors.push("ten_xa is required and must be a non-empty string");
        }
        if (!data.chief || typeof data.chief !== "string" || data.chief.trim() === "") {
            errors.push("chief is required and must be a non-empty string");
        }
        if (data.cap === undefined || data.cap === null || typeof data.cap !== "number") {
            errors.push("cap is required and must be a number");
        }
    }

    // Optional fields validation
    if (data.ma_xa !== undefined) {
        if (typeof data.ma_xa !== "string" || data.ma_xa.trim() === "") {
            errors.push("ma_xa must be a non-empty string");
        }
    }

    if (data.ten_xa !== undefined) {
        if (typeof data.ten_xa !== "string" || data.ten_xa.trim() === "") {
            errors.push("ten_xa must be a non-empty string");
        }
    }

    if (data.chief !== undefined) {
        if (typeof data.chief !== "string" || data.chief.trim() === "") {
            errors.push("chief must be a non-empty string");
        }
    }

    if (data.mobile !== undefined && data.mobile !== null) {
        if (typeof data.mobile !== "string") {
            errors.push("mobile must be a string or null");
        }
    }

    if (data.cap !== undefined && data.cap !== null) {
        if (typeof data.cap !== "number") {
            errors.push("cap must be a number");
        }
    }

    return {
        isValid: errors.length === 0,
        errors
    };
};

/**
 * Sanitize contact data - loại bỏ các field không hợp lệ
 */
const sanitizeContactData = (data) => {
    const allowedFields = [
        "ma_xa",
        "ten_xa",
        "chief",
        "mobile",
        "cap"
    ];

    const sanitized = {};
    for (const field of allowedFields) {
        if (data[field] !== undefined) {
            sanitized[field] = data[field];
        }
    }

    return sanitized;
};

/**
 * Get default contact data
 */
const getDefaultContactData = () => {
    return {
        mobile: null
    };
};

module.exports = {
    CONTACT_SCHEMA,
    validateContact,
    sanitizeContactData,
    getDefaultContactData
};

