/**
 * Login Identifier Schema Definition for Firebase Firestore
 *
 * Collection: login_identifiers
 *
 * Ánh xạ số điện thoại đăng nhập → Firebase Auth email.
 * CBCS nhập SĐT + mật khẩu → Cloud Function tra bảng này → đăng nhập Firebase bằng authEmail.
 */

const crypto = require("crypto");

const COLLECTION_NAME = "login_identifiers";
const IDENTIFIER_TYPE = "phone";
const ID_PREFIX = "phone_";

const FIRESTORE_INDEXES = [
    "phoneNormalized",
    "phoneHash",
    "firebaseUid",
    "authEmail",
    "accountStatus",
];

const LOGIN_IDENTIFIER_SCHEMA = {
    _id: {
        type: "string",
        required: true,
        description: "Document ID dạng phone_{phoneNormalized}, ví dụ phone_84912345678",
    },
    type: {
        type: "string",
        required: true,
        enum: ["phone"],
        default: "phone",
    },
    phone: {
        type: "string",
        required: true,
        description: "Số điện thoại hiển thị, ví dụ 0912345678",
    },
    phoneNormalized: {
        type: "string",
        required: true,
        unique: true,
        description: "Số điện thoại chuẩn hóa, ví dụ 84912345678",
    },
    phoneHash: {
        type: "string",
        required: true,
        description: "SHA-256 hash của phoneNormalized",
    },
    firebaseUid: {
        type: "string",
        required: true,
        ref: "app_users._id",
    },
    authEmail: {
        type: "string",
        required: true,
        description: "Email dùng đăng nhập Firebase Auth",
    },
    accountStatus: {
        type: "string",
        required: true,
        description: "Đồng bộ với app_users.status.accountStatus",
    },
    createdAt: {
        type: "timestamp",
        autoGenerated: true,
    },
    updatedAt: {
        type: "timestamp",
        autoGenerated: true,
    },
};

/**
 * Chuẩn hóa số điện thoại Việt Nam → dạng 84xxxxxxxxx
 */
const normalizePhone = (phone) => {
    let digits = String(phone).replace(/\D/g, "");

    if (digits.startsWith("84")) {
        // giữ nguyên
    } else if (digits.startsWith("0")) {
        digits = `84${digits.slice(1)}`;
    } else {
        digits = `84${digits}`;
    }

    const displayPhone = digits.startsWith("84")
        ? `0${digits.slice(2)}`
        : digits;

    return {
        phone: displayPhone,
        phoneNormalized: digits,
    };
};

const hashPhone = (phoneNormalized) => {
    return crypto.createHash("sha256").update(phoneNormalized).digest("hex");
};

const buildLoginIdentifierId = (phoneNormalized) => {
    return `${ID_PREFIX}${phoneNormalized}`;
};

const validateLoginIdentifier = (data, isUpdate = false) => {
    const errors = [];

    if (!isUpdate) {
        if (!data.type || data.type !== IDENTIFIER_TYPE) {
            errors.push(`type must be '${IDENTIFIER_TYPE}'`);
        }
        if (!data.phone || typeof data.phone !== "string") {
            errors.push("phone is required");
        }
        if (!data.phoneNormalized || typeof data.phoneNormalized !== "string") {
            errors.push("phoneNormalized is required");
        }
        if (!data.phoneHash || typeof data.phoneHash !== "string") {
            errors.push("phoneHash is required");
        }
        if (!data.firebaseUid || typeof data.firebaseUid !== "string") {
            errors.push("firebaseUid is required");
        }
        if (data.authEmail !== undefined && data.authEmail !== null && typeof data.authEmail !== "string") {
            errors.push("authEmail must be a string or null");
        }
        if (!data.accountStatus || typeof data.accountStatus !== "string") {
            errors.push("accountStatus is required");
        }
    }

    return {
        isValid: errors.length === 0,
        errors,
    };
};

/**
 * Build document login_identifiers từ thông tin tài khoản app.
 */
const buildLoginIdentifierDocument = ({
    phone,
    phoneNormalized,
    firebaseUid,
    authEmail,
    accountStatus = "pending_activation",
}) => {
    const normalized = phoneNormalized
        ? { phone, phoneNormalized }
        : normalizePhone(phone);

    const finalPhoneNormalized = normalized.phoneNormalized;

    return {
        type: IDENTIFIER_TYPE,
        phone: normalized.phone,
        phoneNormalized: finalPhoneNormalized,
        phoneHash: hashPhone(finalPhoneNormalized),
        firebaseUid,
        authEmail: authEmail ? authEmail.trim().toLowerCase() : null,
        accountStatus,
    };
};

const getLoginIdentifierDocId = (phoneOrNormalized, isAlreadyNormalized = false) => {
    const phoneNormalized = isAlreadyNormalized
        ? phoneOrNormalized
        : normalizePhone(phoneOrNormalized).phoneNormalized;

    return buildLoginIdentifierId(phoneNormalized);
};

module.exports = {
    COLLECTION_NAME,
    LOGIN_IDENTIFIER_SCHEMA,
    IDENTIFIER_TYPE,
    ID_PREFIX,
    FIRESTORE_INDEXES,
    normalizePhone,
    hashPhone,
    buildLoginIdentifierId,
    validateLoginIdentifier,
    buildLoginIdentifierDocument,
    getLoginIdentifierDocId,
};
