/**
 * User Schema Definition for Firebase Firestore
 * 
 * Đây là file định nghĩa schema cho User trong Firebase.
 * Firebase Firestore không có schema validation tự động như MongoDB,
 * nên file này dùng để:
 * 1. Tham khảo cấu trúc dữ liệu
 * 2. Validation trong code
 * 3. Documentation
 */

const USER_SCHEMA = {
    // Required fields
    userName: {
        type: "string",
        required: true,
        unique: true,
        description: "Tên đăng nhập (duy nhất)"
    },
    password: {
        type: "string",
        required: true,
        description: "Mật khẩu đã được hash bằng bcrypt"
    },
    
    // Optional fields
    refreshToken: {
        type: "string",
        required: false,
        description: "Token để refresh access token"
    },
    
    // Auto-generated fields (Firebase timestamps)
    createdAt: {
        type: "timestamp",
        required: false,
        autoGenerated: true,
        description: "Thời gian tạo (tự động)"
    },
    updatedAt: {
        type: "timestamp",
        required: false,
        autoGenerated: true,
        description: "Thời gian cập nhật (tự động)"
    }
};

/**
 * Validation function cho user data
 */
const validateUser = (data, isUpdate = false) => {
    const errors = [];

    // Required fields khi tạo mới
    if (!isUpdate) {
        if (!data.userName || typeof data.userName !== "string" || data.userName.trim() === "") {
            errors.push("userName is required and must be a non-empty string");
        }
        if (!data.password || typeof data.password !== "string" || data.password.length < 6) {
            errors.push("password is required and must be at least 6 characters");
        }
    }

    // Optional fields validation
    if (data.userName !== undefined) {
        if (typeof data.userName !== "string" || data.userName.trim() === "") {
            errors.push("userName must be a non-empty string");
        }
    }

    if (data.password !== undefined && !isUpdate) {
        if (typeof data.password !== "string" || data.password.length < 6) {
            errors.push("password must be at least 6 characters");
        }
    }

    if (data.refreshToken !== undefined && typeof data.refreshToken !== "string") {
        errors.push("refreshToken must be a string");
    }

    return {
        isValid: errors.length === 0,
        errors
    };
};

/**
 * Sanitize user data - loại bỏ các field không hợp lệ
 */
const sanitizeUserData = (data) => {
    const allowedFields = [
        "userName",
        "password",
        "refreshToken"
    ];

    const sanitized = {};
    for (const field of allowedFields) {
        if (data[field] !== undefined) {
            sanitized[field] = data[field];
        }
    }

    return sanitized;
};

/**
 * Get default user data
 */
const getDefaultUserData = () => {
    return {};
};

module.exports = {
    USER_SCHEMA,
    validateUser,
    sanitizeUserData,
    getDefaultUserData
};

